# 在这里编写springboot的配置信息
server:
  port: 8085
zipkin:
  serviceName: dubboprovider
  zipkinurl: http://127.0.0.1:9411/api/v2/spans
  connectTimeout: 6000
  readTimeout: 6000
  flushInterval: 1
  compressionEnabled: true
  rate: 1.0
